# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus_proto/v1/capability.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'janus_proto/v1/capability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fjanus_proto/v1/capability.proto\x12\x0ejanus_proto.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"o\n\x0b\x43\x61\x63hePolicy\x12\x33\n\x04kind\x18\x01 \x01(\x0e\x32\x1f.janus_proto.v1.CachePolicyKindR\x04kind\x12+\n\x03ttl\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationR\x03ttl\"\xb8\x04\n\x14\x43\x61pabilityDescriptor\x12#\n\rcapability_id\x18\x01 \x01(\tR\x0c\x63\x61pabilityId\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12.\n\x13input_content_types\x18\x04 \x03(\tR\x11inputContentTypes\x12\x30\n\x14output_content_types\x18\x05 \x03(\tR\x12outputContentTypes\x12:\n\x0cinput_schema\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructR\x0binputSchema\x12<\n\routput_schema\x18\x07 \x01(\x0b\x32\x17.google.protobuf.StructR\x0coutputSchema\x12>\n\x0c\x63\x61\x63he_policy\x18\x08 \x01(\x0b\x32\x1b.janus_proto.v1.CachePolicyR\x0b\x63\x61\x63hePolicy\x12\x1e\n\nidempotent\x18\t \x01(\x08R\nidempotent\x12H\n\x06labels\x18\n \x03(\x0b\x32\x30.janus_proto.v1.CapabilityDescriptor.LabelsEntryR\x06labels\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01*k\n\x0f\x43\x61\x63hePolicyKind\x12!\n\x1d\x43\x41\x43HE_POLICY_KIND_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x43\x41\x43HE_POLICY_KIND_NONE\x10\x01\x12\x19\n\x15\x43\x41\x43HE_POLICY_KIND_TTL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus_proto.v1.capability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITYDESCRIPTOR_LABELSENTRY']._loaded_options = None
  _globals['_CAPABILITYDESCRIPTOR_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_CACHEPOLICYKIND']._serialized_start=797
  _globals['_CACHEPOLICYKIND']._serialized_end=904
  _globals['_CACHEPOLICY']._serialized_start=113
  _globals['_CACHEPOLICY']._serialized_end=224
  _globals['_CAPABILITYDESCRIPTOR']._serialized_start=227
  _globals['_CAPABILITYDESCRIPTOR']._serialized_end=795
  _globals['_CAPABILITYDESCRIPTOR_LABELSENTRY']._serialized_start=738
  _globals['_CAPABILITYDESCRIPTOR_LABELSENTRY']._serialized_end=795
# @@protoc_insertion_point(module_scope)
