# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus_proto/v1/common.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'janus_proto/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjanus_proto/v1/common.proto\x12\x0ejanus_proto.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x93\x01\n\x07Payload\x12\x14\n\x04text\x18\x01 \x01(\tH\x00R\x04text\x12-\n\x04json\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x00R\x04json\x12\x18\n\x06\x62inary\x18\x03 \x01(\x0cH\x00R\x06\x62inary\x12!\n\x0c\x63ontent_type\x18\x04 \x01(\tR\x0b\x63ontentTypeB\x06\n\x04kind\"\xa4\x02\n\x08\x41rtifact\x12\x1f\n\x0b\x61rtifact_id\x18\x01 \x01(\tR\nartifactId\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n\x03uri\x18\x03 \x01(\tR\x03uri\x12!\n\x0c\x63ontent_type\x18\x04 \x01(\tR\x0b\x63ontentType\x12\x1d\n\nsize_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12\x16\n\x06sha256\x18\x06 \x01(\tR\x06sha256\x12<\n\x06labels\x18\x07 \x03(\x0b\x32$.janus_proto.v1.Artifact.LabelsEntryR\x06labels\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x89\x02\n\tErrorInfo\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x1c\n\tretryable\x18\x03 \x01(\x08R\tretryable\x12\x32\n\x15side_effects_possible\x18\x04 \x01(\x08R\x13sideEffectsPossible\x12@\n\x07\x64\x65tails\x18\x05 \x03(\x0b\x32&.janus_proto.v1.ErrorInfo.DetailsEntryR\x07\x64\x65tails\x1a:\n\x0c\x44\x65tailsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus_proto.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTIFACT_LABELSENTRY']._loaded_options = None
  _globals['_ARTIFACT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_ERRORINFO_DETAILSENTRY']._loaded_options = None
  _globals['_ERRORINFO_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_PAYLOAD']._serialized_start=78
  _globals['_PAYLOAD']._serialized_end=225
  _globals['_ARTIFACT']._serialized_start=228
  _globals['_ARTIFACT']._serialized_end=520
  _globals['_ARTIFACT_LABELSENTRY']._serialized_start=463
  _globals['_ARTIFACT_LABELSENTRY']._serialized_end=520
  _globals['_ERRORINFO']._serialized_start=523
  _globals['_ERRORINFO']._serialized_end=788
  _globals['_ERRORINFO_DETAILSENTRY']._serialized_start=730
  _globals['_ERRORINFO_DETAILSENTRY']._serialized_end=788
# @@protoc_insertion_point(module_scope)
