# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from janus_proto.v1 import gateway_pb2 as janus__proto_dot_v1_dot_gateway__pb2
from janus_proto.v1 import semantic_pb2 as janus__proto_dot_v1_dot_semantic__pb2
from janus_proto.v1 import session_pb2 as janus__proto_dot_v1_dot_session__pb2
from janus_proto.v1 import spoke_pb2 as janus__proto_dot_v1_dot_spoke__pb2
from janus_proto.v1 import task_pb2 as janus__proto_dot_v1_dot_task__pb2


class SpokeGatewayStub(object):
    """Implemented by apps/core-gateway. Tokens travel in gRPC metadata
    (`authorization`), never in messages. Scopes are enforced by spec 05 and
    spec 11; each RPC below documents the one it requires.

    Spoke to core. Auth: token with scope registry:register or
    capability:invoke, as noted per RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/janus_proto.v1.SpokeGateway/Register',
                request_serializer=janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/janus_proto.v1.SpokeGateway/Heartbeat',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.HealthAck.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/janus_proto.v1.SpokeGateway/Unregister',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestCapability = channel.unary_stream(
                '/janus_proto.v1.SpokeGateway/RequestCapability',
                request_serializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.FromString,
                _registered_method=True)


class SpokeGatewayServicer(object):
    """Implemented by apps/core-gateway. Tokens travel in gRPC metadata
    (`authorization`), never in messages. Scopes are enforced by spec 05 and
    spec 11; each RPC below documents the one it requires.

    Spoke to core. Auth: token with scope registry:register or
    capability:invoke, as noted per RPC.
    """

    def Register(self, request, context):
        """Scope: registry:register.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Scope: registry:register.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Scope: registry:register.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCapability(self, request, context):
        """Spoke asking the core for a capability. Scope: capability:invoke.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpokeGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.HeartbeatRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.HealthAck.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestCapability': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestCapability,
                    request_deserializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus_proto.v1.SpokeGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus_proto.v1.SpokeGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpokeGateway(object):
    """Implemented by apps/core-gateway. Tokens travel in gRPC metadata
    (`authorization`), never in messages. Scopes are enforced by spec 05 and
    spec 11; each RPC below documents the one it requires.

    Spoke to core. Auth: token with scope registry:register or
    capability:invoke, as noted per RPC.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.SpokeGateway/Register',
            janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.SpokeGateway/Heartbeat',
            janus__proto_dot_v1_dot_gateway__pb2.HeartbeatRequest.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.HealthAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.SpokeGateway/Unregister',
            janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/janus_proto.v1.SpokeGateway/RequestCapability',
            janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.SerializeToString,
            janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChannelBridgeStub(object):
    """channel-gateway to core. Auth: internal channel-gateway token.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/janus_proto.v1.ChannelBridge/Stream',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.ChannelUp.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.ChannelDown.FromString,
                _registered_method=True)


class ChannelBridgeServicer(object):
    """channel-gateway to core. Auth: internal channel-gateway token.
    """

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.ChannelUp.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.ChannelDown.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus_proto.v1.ChannelBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus_proto.v1.ChannelBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelBridge(object):
    """channel-gateway to core. Auth: internal channel-gateway token.
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/janus_proto.v1.ChannelBridge/Stream',
            janus__proto_dot_v1_dot_gateway__pb2.ChannelUp.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.ChannelDown.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ControlStub(object):
    """Administrative operations. Scope: control:write on every RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/janus_proto.v1.Control/CreateTask',
                request_serializer=janus__proto_dot_v1_dot_task__pb2.TaskSpec.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/janus_proto.v1.Control/CancelTask',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.PauseTask = channel.unary_unary(
                '/janus_proto.v1.Control/PauseTask',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.ResumeTask = channel.unary_unary(
                '/janus_proto.v1.Control/ResumeTask',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_task__pb2.Task.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/janus_proto.v1.Control/AssignRole',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/janus_proto.v1.Control/CreateSession',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_session__pb2.Session.FromString,
                _registered_method=True)
        self.SubscribeSession = channel.unary_unary(
                '/janus_proto.v1.Control/SubscribeSession',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_session__pb2.Session.FromString,
                _registered_method=True)
        self.UnsubscribeSession = channel.unary_unary(
                '/janus_proto.v1.Control/UnsubscribeSession',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_session__pb2.Session.FromString,
                _registered_method=True)
        self.SetPreference = channel.unary_unary(
                '/janus_proto.v1.Control/SetPreference',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.SetPreferenceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetSpokeAvailability = channel.unary_unary(
                '/janus_proto.v1.Control/SetSpokeAvailability',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.SetSpokeAvailabilityRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RegisterSpoke = channel.unary_unary(
                '/janus_proto.v1.Control/RegisterSpoke',
                request_serializer=janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.FromString,
                _registered_method=True)
        self.RetireSpoke = channel.unary_unary(
                '/janus_proto.v1.Control/RetireSpoke',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ControlServicer(object):
    """Administrative operations. Scope: control:write on every RPC.
    """

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpokeAvailability(self, request, context):
        """Spec 17.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSpoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetireSpoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=janus__proto_dot_v1_dot_task__pb2.TaskSpec.FromString,
                    response_serializer=janus__proto_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.FromString,
                    response_serializer=janus__proto_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'PauseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTask,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.FromString,
                    response_serializer=janus__proto_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'ResumeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTask,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.TaskRef.FromString,
                    response_serializer=janus__proto_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.AssignRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.CreateSessionRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_session__pb2.Session.SerializeToString,
            ),
            'SubscribeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeSession,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_session__pb2.Session.SerializeToString,
            ),
            'UnsubscribeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeSession,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_session__pb2.Session.SerializeToString,
            ),
            'SetPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreference,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.SetPreferenceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetSpokeAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpokeAvailability,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.SetSpokeAvailabilityRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RegisterSpoke': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSpoke,
                    request_deserializer=janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.SerializeToString,
            ),
            'RetireSpoke': grpc.unary_unary_rpc_method_handler(
                    servicer.RetireSpoke,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus_proto.v1.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus_proto.v1.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Administrative operations. Scope: control:write on every RPC.
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/CreateTask',
            janus__proto_dot_v1_dot_task__pb2.TaskSpec.SerializeToString,
            janus__proto_dot_v1_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/CancelTask',
            janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
            janus__proto_dot_v1_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/PauseTask',
            janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
            janus__proto_dot_v1_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/ResumeTask',
            janus__proto_dot_v1_dot_gateway__pb2.TaskRef.SerializeToString,
            janus__proto_dot_v1_dot_task__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/AssignRole',
            janus__proto_dot_v1_dot_gateway__pb2.AssignRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/CreateSession',
            janus__proto_dot_v1_dot_gateway__pb2.CreateSessionRequest.SerializeToString,
            janus__proto_dot_v1_dot_session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/SubscribeSession',
            janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.SerializeToString,
            janus__proto_dot_v1_dot_session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/UnsubscribeSession',
            janus__proto_dot_v1_dot_gateway__pb2.SubscribeRequest.SerializeToString,
            janus__proto_dot_v1_dot_session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/SetPreference',
            janus__proto_dot_v1_dot_gateway__pb2.SetPreferenceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpokeAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/SetSpokeAvailability',
            janus__proto_dot_v1_dot_gateway__pb2.SetSpokeAvailabilityRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSpoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/RegisterSpoke',
            janus__proto_dot_v1_dot_spoke__pb2.SpokeRegistration.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.RegisterAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetireSpoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Control/RetireSpoke',
            janus__proto_dot_v1_dot_gateway__pb2.UnregisterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObserveStub(object):
    """Read only state. Scope: observe:read on every RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRegistry = channel.unary_unary(
                '/janus_proto.v1.Observe/GetRegistry',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.RegistrySnapshot.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/janus_proto.v1.Observe/ListSessions',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.ListRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.SessionList.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/janus_proto.v1.Observe/ListTasks',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.ListRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.TaskList.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/janus_proto.v1.Observe/ListAgents',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.AgentList.FromString,
                _registered_method=True)
        self.GetPreferences = channel.unary_unary(
                '/janus_proto.v1.Observe/GetPreferences',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.PreferenceSet.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/janus_proto.v1.Observe/Watch',
                request_serializer=janus__proto_dot_v1_dot_gateway__pb2.WatchRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_gateway__pb2.StateEvent.FromString,
                _registered_method=True)


class ObserveServicer(object):
    """Read only state. Scope: observe:read on every RPC.
    """

    def GetRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Push events of architecture/07 section 3.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObserveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegistry,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.RegistrySnapshot.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.ListRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.SessionList.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.ListRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.TaskList.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.AgentList.SerializeToString,
            ),
            'GetPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferences,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.PreferenceSet.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=janus__proto_dot_v1_dot_gateway__pb2.WatchRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_gateway__pb2.StateEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus_proto.v1.Observe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus_proto.v1.Observe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Observe(object):
    """Read only state. Scope: observe:read on every RPC.
    """

    @staticmethod
    def GetRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Observe/GetRegistry',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.RegistrySnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Observe/ListSessions',
            janus__proto_dot_v1_dot_gateway__pb2.ListRequest.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Observe/ListTasks',
            janus__proto_dot_v1_dot_gateway__pb2.ListRequest.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.TaskList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Observe/ListAgents',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.AgentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.Observe/GetPreferences',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.PreferenceSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/janus_proto.v1.Observe/Watch',
            janus__proto_dot_v1_dot_gateway__pb2.WatchRequest.SerializeToString,
            janus__proto_dot_v1_dot_gateway__pb2.StateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
