# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus_proto/v1/session.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'janus_proto/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cjanus_proto/v1/session.proto\x12\x0ejanus_proto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n\x0bParticipant\x12%\n\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x33\n\x04kind\x18\x02 \x01(\x0e\x32\x1f.janus_proto.v1.ParticipantKindR\x04kind\x12\x1f\n\x0b\x63hannel_ref\x18\x03 \x01(\tR\nchannelRef\x12\x37\n\tjoined_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08joinedAt\x12\x38\n\x07left_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00R\x06leftAt\x88\x01\x01\x42\n\n\x08_left_at\"\x98\x03\n\x07Session\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12/\n\x04kind\x18\x02 \x01(\x0e\x32\x1b.janus_proto.v1.SessionKindR\x04kind\x12\x1d\n\nagent_name\x18\x03 \x01(\tR\tagentName\x12\x1c\n\x07task_id\x18\x04 \x01(\tH\x00R\x06taskId\x88\x01\x01\x12\x35\n\x06status\x18\x05 \x01(\x0e\x32\x1d.janus_proto.v1.SessionStatusR\x06status\x12\x36\n\x17\x65xternal_listener_count\x18\x06 \x01(\rR\x15\x65xternalListenerCount\x12\x39\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n\tclosed_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01R\x08\x63losedAt\x88\x01\x01\x42\n\n\x08_task_idB\x0c\n\n_closed_at*e\n\x0bSessionKind\x12\x1c\n\x18SESSION_KIND_UNSPECIFIED\x10\x00\x12\x1b\n\x17SESSION_KIND_JANUS_MAIN\x10\x01\x12\x1b\n\x17SESSION_KIND_AGENT_TASK\x10\x02*c\n\rSessionStatus\x12\x1e\n\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13SESSION_STATUS_OPEN\x10\x01\x12\x19\n\x15SESSION_STATUS_CLOSED\x10\x02*\x8f\x01\n\x0fParticipantKind\x12 \n\x1cPARTICIPANT_KIND_UNSPECIFIED\x10\x00\x12\x1a\n\x16PARTICIPANT_KIND_JANUS\x10\x01\x12\x1a\n\x16PARTICIPANT_KIND_AGENT\x10\x02\x12\"\n\x1ePARTICIPANT_KIND_USER_LISTENER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus_proto.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONKIND']._serialized_start=760
  _globals['_SESSIONKIND']._serialized_end=861
  _globals['_SESSIONSTATUS']._serialized_start=863
  _globals['_SESSIONSTATUS']._serialized_end=962
  _globals['_PARTICIPANTKIND']._serialized_start=965
  _globals['_PARTICIPANTKIND']._serialized_end=1108
  _globals['_PARTICIPANT']._serialized_start=82
  _globals['_PARTICIPANT']._serialized_end=347
  _globals['_SESSION']._serialized_start=350
  _globals['_SESSION']._serialized_end=758
# @@protoc_insertion_point(module_scope)
