# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from janus_proto.v1 import semantic_pb2 as janus__proto_dot_v1_dot_semantic__pb2
from janus_proto.v1 import spoke_pb2 as janus__proto_dot_v1_dot_spoke__pb2


class SpokeEndpointStub(object):
    """Implemented by a native spoke that speaks gRPC. The core calls it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_stream(
                '/janus_proto.v1.SpokeEndpoint/Invoke',
                request_serializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/janus_proto.v1.SpokeEndpoint/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=janus__proto_dot_v1_dot_spoke__pb2.HealthReport.FromString,
                _registered_method=True)


class SpokeEndpointServicer(object):
    """Implemented by a native spoke that speaks gRPC. The core calls it.
    """

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpokeEndpointServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_stream_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.FromString,
                    response_serializer=janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=janus__proto_dot_v1_dot_spoke__pb2.HealthReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus_proto.v1.SpokeEndpoint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus_proto.v1.SpokeEndpoint', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpokeEndpoint(object):
    """Implemented by a native spoke that speaks gRPC. The core calls it.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/janus_proto.v1.SpokeEndpoint/Invoke',
            janus__proto_dot_v1_dot_semantic__pb2.SemanticRequest.SerializeToString,
            janus__proto_dot_v1_dot_semantic__pb2.SemanticEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus_proto.v1.SpokeEndpoint/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            janus__proto_dot_v1_dot_spoke__pb2.HealthReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
